# SPDX-FileCopyrightText: 2024 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

name: "Run Gradle on a filter=tree:0 checkout"
runs:
    using: composite
    steps:
        -   uses: actions/checkout@v4
            name: Checkout repository
            with:
                fetch-tags: true
                fetch-depth: 0
                filter: 'tree:0'
        -   name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
                distribution: temurin
                java-version: 21
        -   name: Set up gradle cache
            uses: gradle/actions/setup-gradle@v3
            with:
                add-job-summary-as-pr-comment: 'on-failure'
        -   name: Prepare unpacked Jars
            run: |
                ./gradlew unpackAllJars
            shell: sh
