# SPDX-FileCopyrightText: 2024 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

name: "Setup Gradle for Minecraft 26.2"
description: "Setup Gradle build environment"
runs:
    using: composite
    steps:
        -   uses: actions/checkout@v4
        -   name: Set up JDK 25
            uses: actions/setup-java@v4
            with:
                distribution: temurin
                java-version: 25
        -   name: Set up gradle cache
            uses: gradle/actions/setup-gradle@v3
        -   name: Build project
            run: ./gradlew build
            shell: bash
