# SPDX-FileCopyrightText: 2024 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0

name: "Run Gradle"
description: "Run Gradle build"
runs:
    using: composite
    steps:
        -   uses: actions/checkout@v4
            name: Checkout repository
        -   name: Set up JDK 25
            uses: actions/setup-java@v4
            with:
                distribution: temurin
                java-version: 25
        -   name: Set up gradle cache
            uses: gradle/actions/setup-gradle@v3
            with:
                cache-read-only: false
        -   name: Prepare unpacked Jars
            run: ./gradlew unpackAllJars
            shell: bash
