# SPDX-FileCopyrightText: 2026 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0
fabricmc=https://maven.fabricmc.net/
architectury=https://maven.architectury.dev/
forgemc=https://maven.minecraftforge.net/
neamoeReleases=https://repo.nea.moe/releases/
neamoeMirror=https://repo.nea.moe/mirror/
mavenCentral=https://repo.maven.apache.org/maven2/
gradlePluginPortal=https://plugins.gradle.org/m2/
shedaniel=https://maven.shedaniel.me/
terraformersmc=https://maven.terraformersmc.com/releases/
djdevauth=https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1
bbkr=https://server.bbkr.space/artifactory/libs-release/
neu=https://maven.notenoughupdates.org/releases/
hyixel=https://repo.hypixel.net/repository/Hypixel/
azureaaronSnapshots=https://maven.azureaaron.net/snapshots/
azureaaronReleases=https://maven.azureaaron.net/releases/
curseMaven=https://www.cursemaven.com/
isxander=https://maven.isxander.dev/releases/
parchmentMc=https://maven.parchmentmc.org/
# jitpack can cause issues so whitelist any relevant jitpack files in repo.nea.moe/mirror/ and pull from there
# if you do not have access to that maven, please ask nea to whitelist the files for you and uncomment this jitpack in
# the meantime
# jitpack=https://jitpack.io/

# arguably all of these repos should be mirrored through my servers. that is a later TODO.

