# SPDX-FileCopyrightText: 2026 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: CC0-1.0
fabricmc=https://maven.fabricmc.net/
architectury=https://maven.architectury.dev/
forgemc=https://maven.minecraftforge.net/
neamoeReleases=https://repo.nea.moe/releases/
neamoeMirror=https://repo.nea.moe/mirror/
mavenCentral=https://repo.maven.apache.org/maven2/
gradlePluginPortal=https://plugins.gradle.org/m2/
# jitpack can cause issues so whitelist any relevant jitpack files in repo.nea.moe/mirror/ and pull from there
# jitpack=https://jitpack.io/
