#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Linnea Gräf <nea@nea.moe>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# ARG_POSITIONAL_SINGLE([source-branch],[Branch to cherry-pick commits from],[])
# ARG_POSITIONAL_SINGLE([target-branch],[Branch to cherry-pick commits onto],[])
# ARG_HELP([Port commits from another branch using jj duplicate.])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS


print_help()
{
	printf '%s\n' "Port commits from another branch using jj duplicate."
	printf 'Usage: %s [-h|--help] <source-branch> <target-branch>\n' "$0"
	printf '\t%s\n' "<source-branch>: Branch to cherry-pick commits from"
	printf '\t%s\n' "<target-branch>: Branch to cherry-pick commits onto"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'source-branch' and 'target-branch'"
	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_source_branch _arg_target_branch "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash
set -euo pipefail
echo Porting commits from $_arg_source_branch to $_arg_target_branch
declare -a to_port
while read -r rev; do
	if ! test -n "$(git rev-list --grep "chery-picked-from: $rev" ${_arg_target_branch}...${_arg_source_branch})"; then
		to_port+=("$rev")
		git log -1 --pretty="Going to port %h: %s" $rev
	fi
done <<< "$(git log --reverse --pretty=%H $_arg_source_branch ^$_arg_target_branch)"
if (( ${#to_port[@]} == 0 )); then
	echo Nothing to port
	exit 0
fi
jj --config 'templates.duplicate_description=concat(description.trim_end(), "\n\nchery-picked-from: ", commit_id)' duplicate --onto $_arg_target_branch "${to_port[@]}"
# ] <-- needed because of Argbash
